# Generated by Django 5.0.3 on 2024-03-21 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seznam_slov',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jmeno', models.CharField(max_length=50)),
                ('id_spravce', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slovo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('zaklad', models.CharField(max_length=100)),
                ('preklad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slozka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jmeno', models.CharField(max_length=50)),
                ('id_spravce', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Trida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jmeno', models.CharField(max_length=50)),
                ('id_spravce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
