# Generated by Django 5.0.3 on 2024-03-21 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seznam_slov_slovo_slozka_alter_user_id_trida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seznam_slov',
            name='id_spravce',
        ),
        migrations.RemoveField(
            model_name='slozka',
            name='id_spravce',
        ),
        migrations.AddField(
            model_name='seznam_slov',
            name='id_vlastnik',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slozka',
            name='id_vlastnik',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slozka',
            name='trida_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.trida'),
        ),
        migrations.CreateModel(
            name='Slozka_Seznam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seznam_slov_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.seznam_slov')),
                ('slozka_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.slozka')),
            ],
        ),
        migrations.CreateModel(
            name='Trida_Seznam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seznam_slov_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.seznam_slov')),
                ('trida_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.trida')),
            ],
        ),
        migrations.CreateModel(
            name='Uspesnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaklad', models.BooleanField(default=True)),
                ('slovo_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.slovo')),
                ('uzivatel_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatel_Seznam_slov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prava', models.BooleanField(default=False)),
                ('cas', models.DateField()),
                ('seznam_slov_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.seznam_slov')),
                ('uzivatel_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatel_Trida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prava', models.BooleanField(default=False)),
                ('trida_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.trida')),
                ('uzivatel_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
