# Generated by Django 5.0.3 on 2024-03-31 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_seznam_slov_id_spravce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('base', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='trida_seznam',
            name='seznam_slov_id',
        ),
        migrations.RemoveField(
            model_name='uzivatel_seznam_slov',
            name='seznam_slov_id',
        ),
        migrations.RemoveField(
            model_name='slozka_seznam',
            name='seznam_slov_id',
        ),
        migrations.RemoveField(
            model_name='uspesnost',
            name='slovo_id',
        ),
        migrations.RemoveField(
            model_name='slozka',
            name='id_vlastnik',
        ),
        migrations.RemoveField(
            model_name='slozka',
            name='trida_id',
        ),
        migrations.RemoveField(
            model_name='slozka_seznam',
            name='slozka_id',
        ),
        migrations.RemoveField(
            model_name='trida',
            name='id_spravce',
        ),
        migrations.RemoveField(
            model_name='uzivatel_trida',
            name='trida_id',
        ),
        migrations.RemoveField(
            model_name='trida_seznam',
            name='trida_id',
        ),
        migrations.RemoveField(
            model_name='uspesnost',
            name='uzivatel_id',
        ),
        migrations.RemoveField(
            model_name='uzivatel_seznam_slov',
            name='uzivatel_id',
        ),
        migrations.RemoveField(
            model_name='uzivatel_trida',
            name='uzivatel_id',
        ),
        migrations.CreateModel(
            name='User_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('owner_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.user_group')),
            ],
        ),
        migrations.CreateModel(
            name='User_User_group_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False)),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.user_group')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Success_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successfuly_translated', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.word')),
            ],
        ),
        migrations.CreateModel(
            name='Word_set',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('owner_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='word_set_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.word_set'),
        ),
        migrations.CreateModel(
            name='User_Word_set_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False)),
                ('last_view', models.DateField()),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_set_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.word_set')),
            ],
        ),
        migrations.CreateModel(
            name='User_group_Word_set_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.user_group')),
                ('word_set_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.word_set')),
            ],
        ),
        migrations.CreateModel(
            name='Folder_Word_set_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.folder')),
                ('word_set_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.word_set')),
            ],
        ),
        migrations.DeleteModel(
            name='Seznam_slov',
        ),
        migrations.DeleteModel(
            name='Slovo',
        ),
        migrations.DeleteModel(
            name='Slozka',
        ),
        migrations.DeleteModel(
            name='Slozka_Seznam',
        ),
        migrations.DeleteModel(
            name='Trida',
        ),
        migrations.DeleteModel(
            name='Trida_Seznam',
        ),
        migrations.DeleteModel(
            name='Uspesnost',
        ),
        migrations.DeleteModel(
            name='Uzivatel_Seznam_slov',
        ),
        migrations.DeleteModel(
            name='Uzivatel_Trida',
        ),
    ]
