# Generated by Django 5.0.3 on 2024-04-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_word_set_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='base',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=1000),
        ),
    ]
