# Generated by Django 5.0.3 on 2024-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_word_base_alter_word_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_rate',
            name='successfuly_translated',
            field=models.BooleanField(default=False),
        ),
    ]
